version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/smartdesk-ai
      - JWT_SECRET=change_this
      - GEMINI_API_KEY=your_key
      - NODE_ENV=production
    depends_on:
      - mongo
    command: npm run dev
  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
